import { Inter } from 'next/font/google'
import './globals.css'
import CustomNavbar from '@/components/CustomNavbar'
import Footer from '@/components/footer'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import UserProfile from './profile/user/page';
import UserProvider from '@/context/userProvider';
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-black text-white'>
     
      <UserProvider>
      <ToastContainer/>
        <CustomNavbar/>
        <div className=''>{children}</div>
        <Footer/>
      </UserProvider>
       
        </body>
    </html>
  )
}
